// The open workspace, generated by the workspace plugin (server/workspace.ts).
declare module 'virtual:workspace' {
  /** The workspace's display name. */
  export const name: string
  /** The plan that opens without ?plan=; its main layout is layouts/decor.json. */
  export const defaultPlan: string
  /** Every plan in the workspace, unchecked, by id (its file name). */
  export const plans: Record<string, unknown>
}
